[package]
name = "twitter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egg-mode = "0.16.1"
tokio = { version = "1.0.0", features = ["full"] }
log = "0.4"
fern = "0.6"
futures = "0.3.30"
